version: "3.8"

services:
  summarizer:
    build: .
    container_name: big5_summarizer
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
#    command: ["python", "big5_summary_connect_ELK.py"]
    networks:
      - elastic

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
      - SERVER_HOST=0.0.0.0
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge